### ISSUE TITLE
Contact's form display or even a Module ?

### ISSUE THREAD

**Issue by pepperstreet** [WebTolk/WT-Contact-with-fields-Joomla-5-package#2]
Hello, as far as I understand the plugin description, it is not possible to show and render the contact form, right!? 
Wouldn't it be nice to have the contact form as well? Luckily Joomla has a build-in form capability, which most other CMS's do not supply. Unfortunately Joomla shows it on the contact component view only. It really lacks a core contact Module incl. form display. 

Any chance to render the form as well? 
Additionally, do you have any plans to turn your plugin into a module too? 

best regards, 
Maik

**Comment by sergeytolkachyov** [comment]
This plugin really only displays information from a contact, but does not display a feedback form for that contact. At the moment, I haven't even thought about using the plugin as a feedback form, since I use [Radical Form plugin](https://hika.su/rasshireniya/radical-form) ([GitHub](https://github.com/Delo-Design/radicalform)) in my work, which gives me a lot of flexibility and a lot of possibilities. I would advise you to pay attention to it. The documentation is in Russian, but with the help of Google Translate it will be quite understandable.
